### ISSUE TITLE
Stopped working with latest update.

### ISSUE THREAD

**Issue by pelmered** [mshytikov/jira-shortcut#1]
First of all, thanks a lot for this great extension! I use it a lot.

However, It seams like it has stopped working after your latest updates. The icon is completely gone and icon for capturing the ticket name is gone from the URL-field. 

I have version 5.0.2 which is the latest commit from today here on GitHub. I use Chrome version 48.0.2564.97 (64-bit) (the latest version) on Mac OSX El Capitan.

Any ideas? Any steps I should take to debug?

**Comment by mshytikov** [comment]
@pelmered Thank you for reporting.
Could you please try the following steps:
1. Restart chrome.
2. Go to  options page `chrome-extension://kjofpimpbjninggehnclcgkgniacejha/options.html`
3. Click 'add rule'  and then 'save' 
4. Go to https://issues.apache.org/jira/browse/HADOOP-3629

As result you should see the icon in the address bar. 
Does it work for you?

**Comment by pelmered** [comment]
@mshytikov: Yes, works good now. Thank you!

**Comment by mshytikov** [comment]
@pelmered  :+1:  Thanks, sorry for inconvenience. 
Do you need more help with it? Or I can consider the issue as closed?

**Comment by pelmered** [comment]
No problem @mshytikov, thank you for a great extension! 
Yes, it works for me now at least so I'll close this issue.
