### ISSUE TITLE
Unable to copy $html

### ISSUE THREAD

**Issue by ebayer** [mshytikov/jira-shortcut#2]
Hello

I could not get $html pattern to work on chrome 48.0.2564.116 running on Linux Mint. Other patterns such as $url is working, I can confirm this when I only use $url as out pattern. However I get the following text only output string when I use $html: in output pattern in:

`$html:<a href="$url">$2 [$1]</a>`

Document the metrics produced by hadoop [HADOOP-3629]

**Comment by mshytikov** [comment]
Hi @ebayer 

Sorry for late reply.

I have created the temporary google doc for you where you can try and play with it https://goo.gl/6klZey.
The idea behind $html output is when you are pasting - it should paste text which is a clickable link to the original url. 
See the example in the  [doc](https://goo.gl/6klZey) 

Please let me know does it work for you?
If not then I will investigate further with running LInux Mint.
